version: '3.9'
services:
# run postgresql
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGES_VOLUME: ${POSTGRES_VOLUME}
    container_name: postgres_container
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./${POSTGRES_VOLUME}:/var/lib/postgresql/data/
# run pgadmin
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4_container
    ports:
      - "8888:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
